name       : perl-config-autoconf
version    : '0.320'
release    : 12
source     :
    - https://cpan.metacpan.org/authors/id/A/AM/AMBS/Config-AutoConf-0.320.tar.gz : bb57a958ef49d3f7162276dae14a7bd5af43fd1d8513231af35d665459454023
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Config::AutoConf - A module to implement some of AutoConf macros in pure perl.
description: |
    Config::AutoConf - A module to implement some of AutoConf macros in pure perl.
builddeps  :
    - perl-capture-tiny
    - perl-file-slurper
rundeps    :
    - perl-capture-tiny
    - perl-file-slurper
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
