name       : perl-config-autoconf
version    : '0.317'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/Config-AutoConf-0.317.tar.gz : 01e4b22d2fecb7cfd3cc1f4dabe95cd137cf249cc5e38184f88556e5c98a9ce1
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Config::AutoConf - A module to implement some of AutoConf macros in pure
    perl.
description: |
    Config::AutoConf - A module to implement some of AutoConf macros in pure perl.
builddeps  :
    - perl-capture-tiny
    - perl-file-slurp-tiny
rundeps    :
    - perl-capture-tiny
    - perl-file-slurp-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
