name       : perl-config-autoconf
version    : 0.315
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/Config-AutoConf-0.315.tar.gz : 4b3cd1e1a698ba9e5660c047f0a4fe192723d4bc9f768fdea511c2fc73ea6940
license    : Artistic-2.0
component  : programming.perl
summary    : Config::AutoConf - A module to implement some of AutoConf macros in pure perl.
description: |
    Config::AutoConf - A module to implement some of AutoConf macros in pure perl.
builddeps  :
    - perl-capture-tiny
rundeps    :
    - perl-capture-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
