name       : perl-config-autoconf
version    : 0.313
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/R/RE/REHSACK/Config-AutoConf-0.313.tar.gz : 3728867041d1bdbc00dffae5658b831e53f99068d3fbf0e8fb95b82a1953aeee
license    : Artistic-2.0
component  : programming.perl
summary    : Config::AutoConf - A module to implement some of AutoConf macros in pure perl.
description: |
    Config::AutoConf - A module to implement some of AutoConf macros in pure perl.
rundeps    :
    - perl-capture-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
