name       : perl-config-autoconf
version    : '0.318'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/Config-AutoConf-0.318.tar.gz : 33c930feec3003de251ca222abe8bbeb74610ad07f65fc16f27d74d195eeab34
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Config::AutoConf - A module to implement some of AutoConf macros in pure perl.
description: |
    Config::AutoConf - A module to implement some of AutoConf macros in pure perl.
builddeps  :
    - perl-capture-tiny
    - perl-file-slurper
rundeps    :
    - perl-capture-tiny
    - perl-file-slurper
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
