name       : perl-config-autoconf
version    : '0.316'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/Config-AutoConf-0.316.tar.gz : 8e6f4b59a69492e0bac135dec075438a64e53e0445f306a6662ebd28c26bb977
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Config::AutoConf - A module to implement some of AutoConf macros in pure perl.
description: |
    Config::AutoConf - A module to implement some of AutoConf macros in pure perl.
builddeps  :
    - perl-capture-tiny
    - perl-file-slurp-tiny
rundeps    :
    - perl-capture-tiny
    - perl-file-slurp-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
